### ISSUE TITLE
Range Slider

### ISSUE THREAD

**Issue by ChrisRAra** [Code-Pop/Vue-3-Forms#9]
How would you use BaseSlider for range slider? What would the props and events be?

**Comment by marina-mosti** [comment]
Hey @ChrisRAra there's no `BaseSlider` component in this course.
I can't really say what properties you would need or how to build a component, because it depends on your design, requirements, etc. but at the very least you're going to be needing a `min` and `max` property, and the usual `modelValue` for 2 way binding

Good luck :)
